// THIS FILE IS GENERATED BY GULP TASK: "sync-clients"
import {Models, Events, Context, CombinationKey} from "../omnisharp-server";
import {ClientV2} from "../clients/client-v2";
import {ObservationClientBase, CombinationClientBase} from "./composite-client-base";
import {merge, aggregate} from "../decorators";

export class ObservationClientV2<T extends ClientV2> extends ObservationClientBase<T> implements Events.V2 {
    @merge public get autocomplete(): Rx.Observable<Context<Models.AutoCompleteRequest, Models.AutoCompleteResponse[]>> { throw new Error("Implemented by decorator"); }
    @merge public get changebuffer(): Rx.Observable<Context<Models.ChangeBufferRequest, any>> { throw new Error("Implemented by decorator"); }
    @merge public get codecheck(): Rx.Observable<Context<Models.CodeCheckRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get codeformat(): Rx.Observable<Context<Models.CodeFormatRequest, Models.CodeFormatResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get currentfilemembersasflat(): Rx.Observable<Context<Models.MembersFlatRequest, Models.QuickFix[]>> { throw new Error("Implemented by decorator"); }
    @merge public get currentfilemembersastree(): Rx.Observable<Context<Models.MembersTreeRequest, Models.FileMemberTree>> { throw new Error("Implemented by decorator"); }
    @merge public get filesChanged(): Rx.Observable<Context<Models.Request[], Models.FilesChangedResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get findimplementations(): Rx.Observable<Context<Models.FindImplementationsRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get findsymbols(): Rx.Observable<Context<Models.FindSymbolsRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get findusages(): Rx.Observable<Context<Models.FindUsagesRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get fixusings(): Rx.Observable<Context<Models.FixUsingsRequest, Models.FixUsingsResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get formatAfterKeystroke(): Rx.Observable<Context<Models.FormatAfterKeystrokeRequest, Models.FormatRangeResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get formatRange(): Rx.Observable<Context<Models.FormatRangeRequest, Models.FormatRangeResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get getcodeactions(): Rx.Observable<Context<Models.V2.GetCodeActionsRequest, Models.V2.GetCodeActionsResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get gettestcontext(): Rx.Observable<Context<Models.TestCommandRequest, Models.GetTestCommandResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get gotodefinition(): Rx.Observable<Context<Models.GotoDefinitionRequest, Models.GotoDefinitionResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get gotofile(): Rx.Observable<Context<Models.GotoFileRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get gotoregion(): Rx.Observable<Context<Models.GotoRegionRequest, Models.QuickFixResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get highlight(): Rx.Observable<Context<Models.HighlightRequest, Models.HighlightResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get metadata(): Rx.Observable<Context<Models.MetadataRequest, Models.MetadataResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get navigatedown(): Rx.Observable<Context<Models.NavigateDownRequest, Models.NavigateResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get navigateup(): Rx.Observable<Context<Models.NavigateUpRequest, Models.NavigateResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get packagesearch(): Rx.Observable<Context<Models.PackageSearchRequest, Models.PackageSearchResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get packagesource(): Rx.Observable<Context<Models.PackageSourceRequest, Models.PackageSourceResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get packageversion(): Rx.Observable<Context<Models.PackageVersionRequest, Models.PackageVersionResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get project(): Rx.Observable<Context<Models.v1.ProjectInformationRequest, Models.ProjectInformationResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get projects(): Rx.Observable<Context<Models.v1.WorkspaceInformationRequest, Models.WorkspaceInformationResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get rename(): Rx.Observable<Context<Models.RenameRequest, Models.RenameResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get runcodeaction(): Rx.Observable<Context<Models.V2.RunCodeActionRequest, Models.V2.RunCodeActionResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get signatureHelp(): Rx.Observable<Context<Models.SignatureHelpRequest, Models.SignatureHelp>> { throw new Error("Implemented by decorator"); }
    @merge public get typelookup(): Rx.Observable<Context<Models.TypeLookupRequest, Models.TypeLookupResponse>> { throw new Error("Implemented by decorator"); }
    @merge public get updatebuffer(): Rx.Observable<Context<Models.UpdateBufferRequest, any>> { throw new Error("Implemented by decorator"); }
}

export class AggregateClientV2<T extends ClientV2> extends CombinationClientBase<T> implements Events.Aggregate.V2 {
    @aggregate public get autocomplete(): Rx.Observable<CombinationKey<Context<Models.AutoCompleteRequest, Models.AutoCompleteResponse[]>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get changebuffer(): Rx.Observable<CombinationKey<Context<Models.ChangeBufferRequest, any>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get codecheck(): Rx.Observable<CombinationKey<Context<Models.CodeCheckRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get codeformat(): Rx.Observable<CombinationKey<Context<Models.CodeFormatRequest, Models.CodeFormatResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get currentfilemembersasflat(): Rx.Observable<CombinationKey<Context<Models.MembersFlatRequest, Models.QuickFix[]>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get currentfilemembersastree(): Rx.Observable<CombinationKey<Context<Models.MembersTreeRequest, Models.FileMemberTree>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get filesChanged(): Rx.Observable<CombinationKey<Context<Models.Request[], Models.FilesChangedResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get findimplementations(): Rx.Observable<CombinationKey<Context<Models.FindImplementationsRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get findsymbols(): Rx.Observable<CombinationKey<Context<Models.FindSymbolsRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get findusages(): Rx.Observable<CombinationKey<Context<Models.FindUsagesRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get fixusings(): Rx.Observable<CombinationKey<Context<Models.FixUsingsRequest, Models.FixUsingsResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get formatAfterKeystroke(): Rx.Observable<CombinationKey<Context<Models.FormatAfterKeystrokeRequest, Models.FormatRangeResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get formatRange(): Rx.Observable<CombinationKey<Context<Models.FormatRangeRequest, Models.FormatRangeResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get getcodeactions(): Rx.Observable<CombinationKey<Context<Models.V2.GetCodeActionsRequest, Models.V2.GetCodeActionsResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get gettestcontext(): Rx.Observable<CombinationKey<Context<Models.TestCommandRequest, Models.GetTestCommandResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get gotodefinition(): Rx.Observable<CombinationKey<Context<Models.GotoDefinitionRequest, Models.GotoDefinitionResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get gotofile(): Rx.Observable<CombinationKey<Context<Models.GotoFileRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get gotoregion(): Rx.Observable<CombinationKey<Context<Models.GotoRegionRequest, Models.QuickFixResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get highlight(): Rx.Observable<CombinationKey<Context<Models.HighlightRequest, Models.HighlightResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get metadata(): Rx.Observable<CombinationKey<Context<Models.MetadataRequest, Models.MetadataResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get navigatedown(): Rx.Observable<CombinationKey<Context<Models.NavigateDownRequest, Models.NavigateResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get navigateup(): Rx.Observable<CombinationKey<Context<Models.NavigateUpRequest, Models.NavigateResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get packagesearch(): Rx.Observable<CombinationKey<Context<Models.PackageSearchRequest, Models.PackageSearchResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get packagesource(): Rx.Observable<CombinationKey<Context<Models.PackageSourceRequest, Models.PackageSourceResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get packageversion(): Rx.Observable<CombinationKey<Context<Models.PackageVersionRequest, Models.PackageVersionResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get project(): Rx.Observable<CombinationKey<Context<Models.v1.ProjectInformationRequest, Models.ProjectInformationResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get projects(): Rx.Observable<CombinationKey<Context<Models.v1.WorkspaceInformationRequest, Models.WorkspaceInformationResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get rename(): Rx.Observable<CombinationKey<Context<Models.RenameRequest, Models.RenameResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get runcodeaction(): Rx.Observable<CombinationKey<Context<Models.V2.RunCodeActionRequest, Models.V2.RunCodeActionResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get signatureHelp(): Rx.Observable<CombinationKey<Context<Models.SignatureHelpRequest, Models.SignatureHelp>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get typelookup(): Rx.Observable<CombinationKey<Context<Models.TypeLookupRequest, Models.TypeLookupResponse>>[]> { throw new Error("Implemented by decorator"); }
    @aggregate public get updatebuffer(): Rx.Observable<CombinationKey<Context<Models.UpdateBufferRequest, any>>[]> { throw new Error("Implemented by decorator"); }
}
