// THIS FILE IS GENERATED BY GULP TASK: "sync-clients"
import * as _ from "lodash";
import {OmnisharpClientOptions} from "../interfaces.d";
import {ProxyClientBase} from "./proxy-client-base";
import {ClientV1, ClientEventsV1} from "../clients/client-v1";
import {proxyProperties} from "./decorators";
import {ClientProxyWrapper} from "./client-proxy-wrapper";

export class ProxyClientV1 extends ProxyClientBase<ClientEventsV1> implements OmniSharp.Api.V1 {
    constructor(_options: OmnisharpClientOptions, _proxy: ClientProxyWrapper) {
        super(_options, c => new ClientEventsV1(c), _proxy);
    }
    public autocomplete: typeof  ClientV1.prototype.autocomplete;
    public changebuffer: typeof  ClientV1.prototype.changebuffer;
    public checkalivestatus: typeof  ClientV1.prototype.checkalivestatus;
    public checkreadystatus: typeof  ClientV1.prototype.checkreadystatus;
    public codecheck: typeof  ClientV1.prototype.codecheck;
    public codeformat: typeof  ClientV1.prototype.codeformat;
    public currentfilemembersasflat: typeof  ClientV1.prototype.currentfilemembersasflat;
    public currentfilemembersastree: typeof  ClientV1.prototype.currentfilemembersastree;
    public filesChanged: typeof  ClientV1.prototype.filesChanged;
    public findimplementations: typeof  ClientV1.prototype.findimplementations;
    public findsymbols: typeof  ClientV1.prototype.findsymbols;
    public findusages: typeof  ClientV1.prototype.findusages;
    public fixusings: typeof  ClientV1.prototype.fixusings;
    public formatAfterKeystroke: typeof  ClientV1.prototype.formatAfterKeystroke;
    public formatRange: typeof  ClientV1.prototype.formatRange;
    public getcodeactions: typeof  ClientV1.prototype.getcodeactions;
    public gettestcontext: typeof  ClientV1.prototype.gettestcontext;
    public gotodefinition: typeof  ClientV1.prototype.gotodefinition;
    public gotofile: typeof  ClientV1.prototype.gotofile;
    public gotoregion: typeof  ClientV1.prototype.gotoregion;
    public highlight: typeof  ClientV1.prototype.highlight;
    public metadata: typeof  ClientV1.prototype.metadata;
    public navigatedown: typeof  ClientV1.prototype.navigatedown;
    public navigateup: typeof  ClientV1.prototype.navigateup;
    public packagesearch: typeof  ClientV1.prototype.packagesearch;
    public packagesource: typeof  ClientV1.prototype.packagesource;
    public packageversion: typeof  ClientV1.prototype.packageversion;
    public project: typeof  ClientV1.prototype.project;
    public projects: typeof  ClientV1.prototype.projects;
    public rename: typeof  ClientV1.prototype.rename;
    public runcodeaction: typeof  ClientV1.prototype.runcodeaction;
    public signatureHelp: typeof  ClientV1.prototype.signatureHelp;
    public stopserver: typeof  ClientV1.prototype.stopserver;
    public typelookup: typeof  ClientV1.prototype.typelookup;
    public updatebuffer: typeof  ClientV1.prototype.updatebuffer;
}
proxyProperties(ProxyClientBase, ProxyClientV1);

