// THIS FILE IS GENERATED BY GULP TASK: "sync-clients"
import * as _ from "lodash";
import {OmnisharpClientOptions} from "../interfaces.d";
import {ProxyClientBase} from "./proxy-client-base";
import {ClientV2, ClientEventsV2} from "../clients/client-v2";
import {proxyProperties} from "./decorators";
import {ClientProxyWrapper} from "./client-proxy-wrapper";

export class ProxyClientV2 extends ProxyClientBase<ClientEventsV2> implements OmniSharp.Api.V2 {
    constructor(_options: OmnisharpClientOptions, _proxy: ClientProxyWrapper) {
        super(_options, c => new ClientEventsV2(c), _proxy);
    }
    public autocomplete: typeof  ClientV2.prototype.autocomplete;
    public changebuffer: typeof  ClientV2.prototype.changebuffer;
    public checkalivestatus: typeof  ClientV2.prototype.checkalivestatus;
    public checkreadystatus: typeof  ClientV2.prototype.checkreadystatus;
    public codecheck: typeof  ClientV2.prototype.codecheck;
    public codeformat: typeof  ClientV2.prototype.codeformat;
    public currentfilemembersasflat: typeof  ClientV2.prototype.currentfilemembersasflat;
    public currentfilemembersastree: typeof  ClientV2.prototype.currentfilemembersastree;
    public filesChanged: typeof  ClientV2.prototype.filesChanged;
    public findimplementations: typeof  ClientV2.prototype.findimplementations;
    public findsymbols: typeof  ClientV2.prototype.findsymbols;
    public findusages: typeof  ClientV2.prototype.findusages;
    public fixusings: typeof  ClientV2.prototype.fixusings;
    public formatAfterKeystroke: typeof  ClientV2.prototype.formatAfterKeystroke;
    public formatRange: typeof  ClientV2.prototype.formatRange;
    public getcodeactions: typeof  ClientV2.prototype.getcodeactions;
    public gettestcontext: typeof  ClientV2.prototype.gettestcontext;
    public gotodefinition: typeof  ClientV2.prototype.gotodefinition;
    public gotofile: typeof  ClientV2.prototype.gotofile;
    public gotoregion: typeof  ClientV2.prototype.gotoregion;
    public highlight: typeof  ClientV2.prototype.highlight;
    public metadata: typeof  ClientV2.prototype.metadata;
    public navigatedown: typeof  ClientV2.prototype.navigatedown;
    public navigateup: typeof  ClientV2.prototype.navigateup;
    public packagesearch: typeof  ClientV2.prototype.packagesearch;
    public packagesource: typeof  ClientV2.prototype.packagesource;
    public packageversion: typeof  ClientV2.prototype.packageversion;
    public project: typeof  ClientV2.prototype.project;
    public projects: typeof  ClientV2.prototype.projects;
    public rename: typeof  ClientV2.prototype.rename;
    public runcodeaction: typeof  ClientV2.prototype.runcodeaction;
    public signatureHelp: typeof  ClientV2.prototype.signatureHelp;
    public stopserver: typeof  ClientV2.prototype.stopserver;
    public typelookup: typeof  ClientV2.prototype.typelookup;
    public updatebuffer: typeof  ClientV2.prototype.updatebuffer;
}
proxyProperties(ProxyClientBase, ProxyClientV2);

